### ISSUE TITLE
Hello been using this in my project for a while..

### ISSUE THREAD

**Issue by TheLoneDeveloper** [Drewdan/paypal#9]
Been using this in my project for a while now but recently have been getting this error.

`Typed property Drewdan\Paypal\Dtos\Order::$status must not be accessed before initialization`

`        $paypalOrder = $order->create($purchaseUnits, 'CAPTURE', $applicationContext);
            if ($paypalOrder->status === 'CREATED') {
               // Rest of code
             } `

Worked perfectly fine a few days ago.

**Comment by KalleNoBody** [comment]
Sorry, I forgot to add the version to the issue,

I'm using version 1.2.0

Here is some more code

`        $purchaseUnits = [
            [
                'amount' => [
                    'currency_code' => 'EUR',
                    'value' => $total,
                    'breakdown' => [
                        'item_total' => array(
                            'currency_code' => 'EUR',
                            'value' => $total,
                        ),
                    ]
                ],
                'items' => $items,
            ]
        ];

        $applicationContext = [
            'brand_name' => 'Test',
            'shipping_preference' => 'NO_SHIPPING',
            'user_action' => 'PAY_NOW',
            'return_url' => route('cart.checkout.paypal.success'),
            'cancel_url' => route('cart.checkout.paypal.cancelled'),
        ];

        $paypalOrder = $order->create($purchaseUnits, 'CAPTURE', $applicationContext);

            if ($paypalOrder->status === 'CREATED') {
                return Inertia::location($paypalOrder->getLinkByRel('approve')->href)
            }`

This exact code worked fine 1-2 weeks ago and nothing changed

**Comment by KalleNoBody** [comment]
> Can you try updating to the latest version? Have you recently changed from sandbox to production mode? I found a bug in 1.2.0 and released a patch with version 1.2.1.
> 
> If that does not fix it, please let me know and we can run through some more debugging steps :)
> 
> Andrew

Updated to 1.2.1 and it now works and yes I switched to production to test if it worked and it did but then I switched back to sandbox mode.

Thank you for your help.
